xys_blog/article/urls.py
from django.urls import path, re_path
from . import views
app_name = 'article'


urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:article_id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:article_id>/', views.article_delete, name='article_delete'),
    path('article-update/<int:article_id>/', views.article_update, name='article_update'),
    path('article-own/', views.article_own, name='article_own'),
    re_path('searchtag/(?P<category>.{0,20})/', views.searchtag, name='searchtag'),
]

xys_blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

xys_blog/xys_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import os


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('photo/', include('photo_gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=os.path.join(settings.MEDIA_ROOT))

xys_blog/article/models.py
from django.db import models
from django import forms
# Create your models here.
# Create your models here.
from django.contrib.auth.models import User
from django.utils import timezone


# BlogArticle文章类
class BlogArticle(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    abstract = models.CharField(max_length=1024)
    body = models.TextField()
    category = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title


class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogArticle
        fields = ('title', 'body', 'category')

xys_blog/article/views.py
from django.shortcuts import render, redirect
from .models import *
from django.http import HttpResponse, HttpResponseRedirect
import markdown
from django.contrib.auth.decorators import login_required


# Create your views here.
def article_list(request):
    if request.user.is_authenticated:
        user_id = request.user.id
        articles = BlogArticle.objects.filter(author_id=user_id)
        # articles = BlogArticle.objects.all()
        context = {'articles': articles}
        return render(request, 'article/list.html', context)
    else:
        articles = BlogArticle.objects.all()
        context = {'articles': articles}
        return render(request, 'article/list.html', context)


# login_required(login_url='/userprofile/login/')
def article_detail(request, article_id):
    article = BlogArticle.objects.get(id=article_id)
    # remark = Remark.objects.filter(aid=id)
    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         'markdown.extensions.extra',
                                         'markdown.extensions.codehilite',
                                         'markdown.extensions.toc',
                                     ])

    # remark = Remark.objects.all()
    # articleReply = ArticleReply.objects.all()
    context = {
        'article': article,
        # 'remark': remark,
        # 'articleReply': articleReply,
    }
    return render(request, 'article/detail.html', context)


@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == "POST":
        article_post_form = BlogForm(data=request.POST)
        if article_post_form.is_valid():
            print(request.POST)
            new_article = article_post_form.save(commit=False)
            user_id = request.user.id
            new_article.author = User.objects.get(id=user_id)
            new_article.save()
            return redirect("article:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        article_post_form = BlogForm()
        context = {'article_post_form': article_post_form}
        return render(request, 'article/create.html', context)


@login_required(login_url='/userprofile/login/')
def article_delete(request, article_id):
    article = BlogArticle.objects.get(id=article_id)
    article.delete()
    return redirect("article:article_list")


@login_required(login_url='/userprofile/login/')
def article_update(request, article_id):
    article = BlogArticle.objects.get(id=article_id)
    if request.method == 'POST':
        article_post_form = BlogForm(data=request.POST)

        if article_post_form .is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()

            return redirect("article:article_detail", id=article_id)
        else:
            return HttpResponse("内容有误，请重新填写")

    else:
        article_post_form = BlogForm()
        context = {'article': article, 'article_post_form': article_post_form}
        return render(request, 'article/update.html', context)


def article_own(request):
    articles = BlogArticle.objects.filter(author_id=request.user.id)
    context = {'articles': articles}
    return render(request, 'article/own.html', context)


def searchtag(request, category):
    tag = category
    articles = BlogArticle.objects.filter(category=category)

    context = {
        'articles':articles,
    }
    return render(request,'article/tag.html',context)

xys_blog/templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">

                    <label for="title">文章分类</label>
                    <input type="text" class="form-control"  id="category" name="category">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

xys_blog/templates/article/detail.html
{% extends "base.html" %}
{%load static %}
{% block title %}
文章详情
{% endblock title%}
{% block content %}
<link href="{% static 'bootstrap/css/mlist.css' %}" rel="stylesheet" type="text/css" />

<!-- 文章详情 -->
<div class="container">
    <div class="row2">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-12 alert alert-success">作者：{{ article.author }}
            {% if user.id == article.author_id %}
           . <a href="#" onclick="confirm_delete()">删除文章</a>
             <a href="{% url 'article:article_update' article.id %}">编辑文章</a>
            {% endif %}
        </div>
        <!-- 文章正文 -->
        <div style="width: 100%; background=#000000; display:block; word-break:break-all; word-wrap:break-word;" class="col-12">
            <p>{{ article.body|safe }}</p>
        </div>

    </div>
    <br/>
    <br/>
    <hr class="hr2" />

    <div class="row">
        {% if user.is_authenticated %}
            我来评论两句~
        {% else %}
            还没登录？快来
        <a href="{% url 'userprofile:login' %}">登录</a>
        吧！
        {% endif %}
    </div>

</div>

<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }
</script>
{% endblock content %}

xys_blog/templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<link href="{% static 'bootstrap/css/mlist.css' %}?v1.0.1" rel="stylesheet" type="text/css" />
<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <div>
                      <span class="box3" >Time:{{ article.created |date:"Y /m /d"}}</span> &nbsp;&nbsp;
                    {% if article.category%}
                        <a class="post-category post-category-js" href="{% url 'article:searchtag' article.category %}">{{ article.category}}</a>
                    {% endif %}
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

xys_blog/templates/article/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论页面</title>
</head>
<body>
<div align="center">评论页面</div>

<form action="../userprofile" method="post">
    {% for field in Remark %}
    {% csrf_token %}
    <div>
        {{ field.label_tag }}:{{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
<div>
    <input type="submit" value="评论">
</div>
</form>

<hr>
{% for tie in ties %}
<div>
    <ul>
        <li>{{ tie.subject }}</li>
        <li>{{ tie.mail }}</li>
        <li>{{ tie.topic }}</li>
        <li>{{ tie.message }}</li>
        <li>{{ tie.cc_myself }}</li>
    </ul>
    <hr>
</div>
{% endfor %}
</body>
</html>

xys_blog/templates/article/own.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    我的博客
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 定义放置文章标题的div容器 -->
<link href="{% static 'bootstrap/css/mlist.css' %}?v1.0.1" rel="stylesheet" type="text/css" />
<div class="container">
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <div>
                     <span class="box3" >Time:{{ article.created |date:"Y /m /d"}}</span>
                    {% if article.category%}
                        <a class="post-category post-category-js" href="{% url 'article:searchtag' article.category %}">{{ article.category}}</a>
                    {% endif %}
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

xys_blog/templates/article/tag.html
{% extends "base.html" %}
{%load static %}
{% block title %}
标签
{% endblock title%}
{% block content %}
<link href="{% static 'bootstrap/css/mlist.css' %}?v1.0.0" rel="stylesheet" type="text/css" /><!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <div>
                     <span class="box3" >Time:{{ article.created |date:"Y /m /d"}}</span> &nbsp;&nbsp;
                 {% if article.category%}
                        <a class="post-category post-category-js" href="{% url 'article:searchtag' article.category %}">{{ article.category}}</a>
                    {% endif %}
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

xys_blog/templates/article/update.html
{% extends "base.html" %} {% load static %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}