xys_blog/article/urls.py
from django.urls import path, re_path
from . import views
app_name = 'article'


urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:article_id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:article_id>/', views.article_delete, name='article_delete'),
    path('article-update/<int:article_id>/', views.article_update, name='article_update'),
    path('article-own/', views.article_own, name='article_own'),
    re_path('searchtag/(?P<category>.{0,20})/', views.searchtag, name='searchtag'),
]

xys_blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

xys_blog/xys_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import os


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('photo/', include('photo_gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=os.path.join(settings.MEDIA_ROOT))

xys_blog/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class XysUser(User):
    security_register_key = models.CharField(max_length=100)

xys_blog/userprofile/forms.py
from django import forms
from .models import XysUser


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class UserRegisterForm(forms.ModelForm):
    # 确认输入的密码
    password = forms.CharField()
    password2 = forms.CharField()
    register_key = forms.CharField()

    class Meta:
        model = XysUser
        fields = ('username', 'email')

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致，请重新输入")

    def check_valid(self):
        data = self.cleaned_data
        if data.get('register_key') == 'loveyuting':
            return True
        else:
            return False

xys_blog/userprofile/views.py
from .forms import UserLoginForm, UserRegisterForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import XysUser


# Create your views here.
def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            data = user_login_form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])

            if user:
                login(request, user)
                return redirect("article:article_list")
            else:
                return HttpResponse("账号或密码输入不合法,请重新输入")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或者POST请求数据")


def user_logout(request):
    logout(request)
    return redirect("userprofile:login")


def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid() and user_register_form.check_valid():
            new_user = user_register_form.save(commit=False)
            new_user.set_password(user_register_form.cleaned_data['password'])

            new_user.save()
            login(request, new_user)
            return redirect("article:article_list")
        else:
            return HttpResponse("注册表单输入有误")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {'form': user_register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或者POST请求")


@login_required(login_url='/userprofile/login/')
def user_delete(request, user_id):
    user = XysUser.objects.get(id=user_id)
    if request.user == user:
        logout(request)
        user.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("你没有删除的权限")

xys_blog/templates/userprofile/login.html
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
                <h5>还没有账号？</h5>
                 <h5>点击<a href='{% url "userprofile:register" %}'>注册账号</a>加入我们吧！</h5>
           <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->

                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
            <br>
            <h5>忘记密码了？</h5>
            <h5>点击<a href='#'>这里</a>重置密码</h5>
        </div>
    </div>
</div>
{% endblock content %}

xys_blog/templates/userprofile/register.html
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">昵称</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 邮箱 -->
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-4">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}