xys_blog/article/urls.py
from django.urls import path, re_path
from . import views
app_name = 'article'


urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:article_id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:article_id>/', views.article_delete, name='article_delete'),
    path('article-update/<int:article_id>/', views.article_update, name='article_update'),
    path('article-own/', views.article_own, name='article_own'),
    re_path('searchtag/(?P<category>.{0,20})/', views.searchtag, name='searchtag'),
]

xys_blog/photo_gallery/urls.py
from django.urls import path, re_path
from . import views


app_name = 'photo_gallery'

urlpatterns = [
    path('gallery/', views.gallery, name='gallery'),
    path('upload-image/', views.upload_image, name='upload_image'),
    path('list-images/', views.list_images, name="list_images"),
    path('del-image/', views.del_image, name='del_image'),
]

xys_blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

xys_blog/xys_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import os


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('photo/', include('photo_gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=os.path.join(settings.MEDIA_ROOT))

xys_blog/templates/base.html
<!DOCTYPE html>
<!-- 载入静态文件 -->
{% load static %}
<!-- 网站主语言 -->
<html lang="zh-cn">
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/code.css' %}">
</head>
<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>

</body>
</html>

xys_blog/templates/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.seafile-shuai.cn 2022</p>
    </div>
</footer>

xys_blog/templates/header.html
<!-- 定义导航栏 -->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <!-- 导航栏商标 -->
    <a  class="navbar-brand" href="{% url 'article:article_own'%}">博客</a>

    <!-- 导航入口 -->
    <div >
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
          <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
          <a class="nav-link" href="{% url 'photo_gallery:list_images' %}">图片管理</a>
          <a class="nav-link" href="{% url 'photo_gallery:gallery' %}">图片墙</a>

              {% if user.is_authenticated %}
        <!-- 如果用户已经登录，则显示用户名下拉框 -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
              <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
            </div>
        </li>

    <!-- 如果用户未登录，则显示 “登录” -->
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
        </li>
    <!-- if 语句在这里结束 -->
           {% endif %}
          <a href="#" >
              <!--<img src="{% static 'image/love.jpg' %}" height="100"> -->
          </a>
      </ul>
    </div>
  </div>
</nav>

{% if user.is_authenticated %}
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    location.href='{% url "userprofile:delete" user.id %}'
                },
            })
        }
    </script>
{% endif %}