xys_blog/article/urls.py
from django.urls import path, re_path
from . import views
app_name = 'article'


urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:article_id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:article_id>/', views.article_delete, name='article_delete'),
    path('article-update/<int:article_id>/', views.article_update, name='article_update'),
    path('article-own/', views.article_own, name='article_own'),
    re_path('searchtag/(?P<category>.{0,20})/', views.searchtag, name='searchtag'),
]

xys_blog/photo_gallery/urls.py
from django.urls import path, re_path
from . import views


app_name = 'photo_gallery'

urlpatterns = [
    path('gallery/', views.gallery, name='gallery'),
    path('upload-image/', views.upload_image, name='upload_image'),
    path('list-images/', views.list_images, name="list_images"),
    path('del-image/', views.del_image, name='del_image'),
]

xys_blog/xys_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import os


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('photo/', include('photo_gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=os.path.join(settings.MEDIA_ROOT))

xys_blog/templates/gallery/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% block content %}
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Photo Gallery</title>
    <link rel="stylesheet" href="{% static '/gallery/css/blueimp-gallery.min.css' %}">
    <link rel="stylesheet" href="{% static '/gallery/style.css' %}">
  </head>
  <body>
    <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
        <div class="slides"></div>
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
    </div>
    <div id="links" class="image-gallery">
      {% if image_list %}
      {% for image in image_list %}
        <a href="/media/{{ image.image}}" title="{{ image.title }}">
            <img src="{{ image.image | thumbnail_url:'avatar' }}" alt="{{ image.title }}">
        </a>
      {% endfor %}
      {% endif %}
    </div>
    <script src="{% static '/gallery/js/blueimp-gallery.min.js' %}"></script>
    <script>
      document.getElementById('links').onclick = function (event) {
          event = event || window.event;
          var target = event.target || event.srcElement,
              link = target.src ? target.parentNode : target,
              options = {index: link, event: event},
              links = this.getElementsByTagName('a');
          blueimp.Gallery(links, options);
      };
    </script>
  </body>
</html>
{% endblock %}

xys_blog/templates/gallery/list_images.html
{% extends "base.html" %}
{% load static %}
{% block title %}images{% endblock %}
{% block content %}
<div>
    <button type="button" class="btn btn-primary btn-lg btn-block" onclick="add_image()"> 添加图片</button>
    <div style="margin-top:10px;">
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>标题</td>
                <td>图片</td>
                <td>预览</td>
                <td>操作</td>
            </tr>
            {% for image in images %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ image.title }}</td>
                <td>{{ image.image }}</td>
                <td><img src="/media/{{ image.image }}" width="100px" height="100px"></td>
                <td>
                    <button type="button"  name="delete" value="{{ image.image }}" class="btn btn-primary" onclick="delete_image(this, {{ image.id }})" >
                        <span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span>
                    </button>
                </td>
            </tr>
            {% empty %}
                <p>还没有图片，请点击上面的按钮添加图片</p>
            {% endfor %}
        </table>
    </div>
</div>

<script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
<script src="{% static 'layer/layer.js' %}"></script>
<script src="https://cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.js"></script>

<script type="text/javascript">
function delete_image(the, image_id){
    var image_title = $(the).parents("tr").children("td").eq(1).text();

    layer.open({
        type: 1,
        skin: "layui-layer-rim",
        area: ["400px", "200px"],
        title: "删除图片",
        content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除一些时间加入的图像</p><span id="content">'+image_title+'</span></div>',
        btn:['确定', '取消'],
        yes: function(){
            var datas = new FormData();
            datas.append("image_id", image_id);
            $.ajax({
                url: '{% url "photo_gallery:del_image" %}',
                type:"POST",
                dataType:'JSON',
                processData: false,// 告诉jQuery不要去处理发送的数据(必须设置
                contentType: false, // 告诉jQuery不要去设置Content-Type请求头（必须设置）
                data: datas,
                success: function(e){
                    var status = e['status']
                    if(status=="1"){
                        parent.location.reload();
                        layer.msg("has been deleted.");
                    }else{
                        layer.msg("删除失败");
                    }
                },
            })
        },
    });
}
</script>
<script type="text/javascript">
function add_image(){
        var index=layer.open({
            type: 1,
            skin: 'layui-layer-demo',
            closeBtn: 0,
            shift: 2,
            shadeClose: true,
            title: "Add Image",
            area: ['800px', '600px'],
            content: "<div style='padding:20px'><p>请新增扩展名是.jpg 或.png 的网上照片地址</p><form enctype='multipart/form-data'><div class='form-group'><label for='phototitle' class='col-sm-2 control-label'>标题</label><div class='col-sm-10'><input id='phototitle' type='text' class='form-control' style='margin-bottom:5px'></div></div><div class='form-group'><label for='photourl' class='col-sm-2 control-label'>地址</label><div class='col-sm-10'><input id='photourl' style='margin-bottom:5px' type='text' class='form-control'></div></div><div><label for='localphotopath' class='col-sm-2 control-label'>文件</label><div class='col-sm-10'><input id='localphotopath' type='file' name='localphotopath' style='margin-bottom:5px'  class='form-control'></div> </div> <div class='form-group'><label for='description' class='col-sm-2 control-label'>描述</label> <div class='col-sm-10'><textarea class='form-control' style='margin-bottom:5px' row='2' id='photodescription'></textarea></div></div><div class='form-group'><div class='col-sm-offset-2 col-sm-10'><input id='newphoto' type='button' class='btn btn-default' value='Add It'></div></div></form></div>",
            success: function(){ $("#newphoto").on('click', function(){
                var title = $("#phototitle").val();
                var url = $("#photourl").val();
                var description = $("#photodescription").val();
                var file = $('#localphotopath')[0].files[0];
                //var photo = {"title":title, "url":url, "description":description};
                var formData=new FormData();
                formData.append('file', file);

                formData.append("title", title);
                formData.append("url", url);
                formData.append("description", description);


                $.ajaxSetup({
                    data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
                });
                $.ajax({
                    url: '{% url "photo_gallery:upload_image" %}',
                    type: 'POST',
                    data: formData,
                    dataType:'JSON',
                    processData: false,// 告诉jQuery不要去处理发送的数据(必须设置
                    contentType: false, // 告诉jQuery不要去设置Content-Type请求头（必须设置）

                    success: function(e){
                        var status = e['status']
                        if(status =="1"){
                            layer.close(index);
                            window.location.reload();
                        } else {
                            layer.msg("图片无法获取，请更换图片");
                        }
                    },
                });
            });
        },
    });
}
</script>


{% endblock %}